set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction vertical  -start_at 247.050 -nets VDD -layer METAL4 -width 2.000 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 245.470 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1.690 -nets VDD -layer METAL4 -width 2.000 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 245.470 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1.690 -nets VDD -layer METAL5 -width 2.000 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 248.050 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 244.470 -nets VDD -layer METAL5 -width 2.000 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 248.050 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 244.760 -nets VSS -layer METAL4 -width 2.000 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 243.180 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 3.980 -nets VSS -layer METAL4 -width 2.000 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 243.180 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 3.980 -nets VSS -layer METAL5 -width 2.000 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 245.760 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 242.180 -nets VSS -layer METAL5 -width 2.000 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 245.760 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal4 straps for net VDD
create_power_straps  -direction vertical  -start_at 28.460 -nets VDD  -layer METAL4 -width 2.000 -pitch_within_group 23.730 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 245.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 51.920 -nets VDD  -layer METAL4 -width 2.000 -pitch_within_group 23.730 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 245.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 75.840 -nets VDD  -layer METAL4 -width 2.000 -pitch_within_group 23.730 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 245.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 99.300 -nets VDD  -layer METAL4 -width 2.000 -pitch_within_group 23.730 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 245.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 123.220 -nets VDD  -layer METAL4 -width 2.000 -pitch_within_group 23.730 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 245.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 147.140 -nets VDD  -layer METAL4 -width 2.000 -pitch_within_group 23.730 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 245.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 170.600 -nets VDD  -layer METAL4 -width 2.000 -pitch_within_group 23.730 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 245.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 194.520 -nets VDD  -layer METAL4 -width 2.000 -pitch_within_group 23.730 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 245.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 217.980 -nets VDD  -layer METAL4 -width 2.000 -pitch_within_group 23.730 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 245.470 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal4 straps for net VSS
create_power_straps  -direction vertical  -start_at 30.760 -nets VSS  -layer METAL4 -width 2.000 -pitch_within_group 23.730 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 243.180 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 54.220 -nets VSS  -layer METAL4 -width 2.000 -pitch_within_group 23.730 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 243.180 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 78.140 -nets VSS  -layer METAL4 -width 2.000 -pitch_within_group 23.730 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 243.180 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 101.600 -nets VSS  -layer METAL4 -width 2.000 -pitch_within_group 23.730 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 243.180 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 125.520 -nets VSS  -layer METAL4 -width 2.000 -pitch_within_group 23.730 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 243.180 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 149.440 -nets VSS  -layer METAL4 -width 2.000 -pitch_within_group 23.730 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 243.180 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 172.900 -nets VSS  -layer METAL4 -width 2.000 -pitch_within_group 23.730 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 243.180 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 196.820 -nets VSS  -layer METAL4 -width 2.000 -pitch_within_group 23.730 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 243.180 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 220.280 -nets VSS  -layer METAL4 -width 2.000 -pitch_within_group 23.730 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 243.180 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VDD
create_power_straps  -direction horizontal  -start_at 27.840 -nets VDD  -layer METAL5 -width 2.000 -pitch_within_group 23.470 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 248.050 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 51.620 -nets VDD  -layer METAL5 -width 2.000 -pitch_within_group 23.470 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 248.050 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 74.990 -nets VDD  -layer METAL5 -width 2.000 -pitch_within_group 23.470 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 248.050 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 98.360 -nets VDD  -layer METAL5 -width 2.000 -pitch_within_group 23.470 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 248.050 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 121.730 -nets VDD  -layer METAL5 -width 2.000 -pitch_within_group 23.470 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 248.050 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 145.510 -nets VDD  -layer METAL5 -width 2.000 -pitch_within_group 23.470 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 248.050 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 168.880 -nets VDD  -layer METAL5 -width 2.000 -pitch_within_group 23.470 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 248.050 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 192.250 -nets VDD  -layer METAL5 -width 2.000 -pitch_within_group 23.470 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 248.050 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 215.620 -nets VDD  -layer METAL5 -width 2.000 -pitch_within_group 23.470 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 248.050 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VSS
create_power_straps  -direction horizontal  -start_at 30.130 -nets VSS  -layer METAL5 -width 2.000 -pitch_within_group 23.470 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 245.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 53.910 -nets VSS  -layer METAL5 -width 2.000 -pitch_within_group 23.470 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 245.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 77.280 -nets VSS  -layer METAL5 -width 2.000 -pitch_within_group 23.470 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 245.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 100.650 -nets VSS  -layer METAL5 -width 2.000 -pitch_within_group 23.470 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 245.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 124.020 -nets VSS  -layer METAL5 -width 2.000 -pitch_within_group 23.470 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 245.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 147.800 -nets VSS  -layer METAL5 -width 2.000 -pitch_within_group 23.470 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 245.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 171.170 -nets VSS  -layer METAL5 -width 2.000 -pitch_within_group 23.470 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 245.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 194.540 -nets VSS  -layer METAL5 -width 2.000 -pitch_within_group 23.470 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 245.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 217.910 -nets VSS  -layer METAL5 -width 2.000 -pitch_within_group 23.470 -start_low_ends coordinate  -start_low_ends_coordinate 2.980 -start_high_ends coordinate  -start_high_ends_coordinate 245.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
